# Generated by Django 6.0.3 on 2026-03-25 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_time', models.TimeField()),
                ('total_pizzas', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opening_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.openingday')),
            ],
            options={
                'ordering': ['pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(choices=[('margherita', 'Naboens Margherita — 80 kr'), ('rustica', 'Naboens Rustica — 90 kr'), ('calabrese', 'Naboens Calabrese — 90 kr'), ('tris', 'Naboens Tris di Formaggi — 95 kr'), ('bambino', 'Naboens Bambino — 85 kr')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
            ],
        ),
    ]
