# Generated by Django 6.0.3 on 2026-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingday',
            name='pizzas_per_slot',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='openingday',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
