# Generated by Django 6.0.3 on 2026-04-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pizza_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
