# Generated by Django 6.0.3 on 2026-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pizza_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='Råvarepris i kr (valgfrit)', null=True),
        ),
    ]
