# Generated by Django 6.0.3 on 2026-04-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pizza_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingday',
            name='pizzas_per_slot',
        ),
        migrations.RemoveField(
            model_name='openingday',
            name='slot_duration_minutes',
        ),
    ]
