# Generated by Django 6.0.3 on 2026-04-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Afventer'), ('ready', 'Klar'), ('paid', 'Betalt')], default='pending', max_length=10),
        ),
    ]
