# Generated by Django 6.0.3 on 2026-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Afventer'), ('igang', 'Igang'), ('ready', 'Klar'), ('paid', 'Betalt')], default='pending', max_length=10),
        ),
    ]
