# Generated by Django 6.0.3 on 2026-04-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orderstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('drink', 'Drikkevare'), ('dessert', 'Dessert'), ('other', 'Andet')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='extras/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.extra')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='core.order')),
            ],
        ),
    ]
