# Generated by Django 6.0.3 on 2026-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_extra_extraorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='Råvarepris i kr (valgfrit)', null=True),
        ),
    ]
