# Generated by Django 6.0.3 on 2026-04-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_extra_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('opening_day', 'pickup_time')},
        ),
    ]
