# Generated by Django 6.0.3 on 2026-04-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_ingredients', to='core.extra')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_ingredients', to='core.ingredient')),
            ],
            options={
                'unique_together': {('extra', 'ingredient')},
            },
        ),
    ]
