# Generated by Django 6.0.3 on 2026-04-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_extraingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingday',
            name='order_deadline',
            field=models.DateTimeField(blank=True, help_text='Tidspunkt hvor bestilling lukker (kan være dage før åbning)', null=True),
        ),
    ]
