# Generated by Django 6.0.3 on 2026-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_openingday_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingday',
            name='order_opens',
            field=models.DateTimeField(blank=True, help_text='Tidspunkt hvor bestilling åbner (tomt = åbner med det samme)', null=True),
        ),
    ]
