# Generated by Django 6.0.3 on 2026-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_openingday_order_opens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
